# Storage for messages - choose a file or mongodb
file: messages.txt
# mongo:
#   addr: mongodb://localhost:27017
#   database: kafka
#   collection: events

# Logger settings
logs:
  level: info
  period: 10s

kafka:
  # Kafka consumer group id
  groupID: group-id

  # List of kafka brokers
  brokers:
    - kafka1.example.com:9092
    - kafka2.example.com:9092
    - kafka3.example.com:9092

  # Kafka topic to read from
  topic: topic

  # Initial offset:
  # -2 for oldest
  # -1 for newest (default)
  # otherwise - timestamp in seconds (integer)
  offset: -1

# Payload fields for filtering messages from kafka
filter:
  field1: value
  field2: 10
  field3: 20.2
  field4: true
  field5: [1, 2, 3]
